remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Fanul - Best Employee 2024
description: Landing Page Project ADI.MS

show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
